config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", :locale => /en|pl/ do
    resource :sessions do
      collection {post :login_attempt }
      end
      root :to => 'sessions#login'
      get "signup", :to => "users#new"
      get "login", :to => "sessions#login"
      get "logout", :to => "sessions#logout"
      get "home", :to => "welcome#index"
      get "profile", :to => 'users#show'
      get "setting", :to => "users#edit"
      resources :users
    
      get 'welcome/index'
      get 'welcome/hidden'
      get 'welcome/search_all'
      get 'welcome/denied', as: 'denied'
      get '/parts/live_search', to: 'parts#live_search', as: 'search'
      get '/pcbs/live_search', to: 'pcbs#live_search', as: 'lookup'
      get '/parts/add_qte', to: 'parts#add_qte', as: 'add_qte'
      get '/parts/del_qte', to: 'parts#del_qte', as: 'del_qte'
      get '/pcbs/add_all', to: 'pcbs#add_all', as: 'add_all'
      get '/shopping_lists/upd_all', to: 'shopping_lists#upd_all', as: 'upd_all'
    
      resources :parts do
        collection {post :import }
        collection {post :move_location }
        collection {post :move_manufacturer }
        collection {post :move_package }
        collection {post :move_type }
        collection {post :add_qte }
        collection {post :set_qte }
        collection {post :del_qte }
        collection {post :add_qte_s }
        collection {post :del_qte_s }
      end
      resources :locations do
      collection {post :import }
      end
      resources :packages do
      collection {post :import }
      end
      resources :manufacturers do
      collection {post :import }
      end
      resources :types do
      collection {post :import }
      end
      
      resources :movies do
      collection {post :import }
      collection {get :call_api }
      end
      resources :mformats do
      collection {post :import }
      end
      resources :mlanguages do
      collection {post :import }
      end
      resources :msubtitles do
      collection {post :import }
      end
      resources :mtypes do
      collection {post :import }
      end
      resources :myears do
      collection {post :import }
      end
      resources :qualities do
      collection {post :import }
      end
      resources :threeds do
      collection {post :import }
      end
      resources :genres
      
      resources :books, :authors, :publishers do
      collection {post :import }
      end
      
      resources :pcbs do
        collection {post :import }
        end
    
      resources :projects do
        collection {post :import }
        end
      
      resources :shopping_lists

  end

  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  EMAIL_REGEX = /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i
  validates :username, :presence => true, :uniqueness => {:case_sensitive => false}, :length => { :in => 3..20 }
  validates :password, :confirmation => true #password_confirmation attr
  has_many :books, dependent: :nullify
  before_save :encrypt_password
  after_save :clear_password
	
	def encrypt_password
	  if password.present?
		self.salt = BCrypt::Engine.generate_salt
		self.encrypted_password= BCrypt::Engine.hash_secret(password, salt)
	  end
	end
	
	def clear_password
	  self.password = nil
	end
	
	def upd_photo(photo)
	 self.photo=photo
	end
	
	def self.authenticate(username_or_email="", login_password="")
	  user = User.find_by_username(username_or_email)
	  if user && user.match_password(login_password)
		return user
	  else
		return false
	  end
	end   
	def match_password(login_password="")
	  if login_password=="" and encrypted_password == nil
		return true
	  else 
		encrypted_password == BCrypt::Engine.hash_secret(login_password, salt)
	  end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	require 'will_paginate/array'
	#skip_before_action :authenticate_user, :only => [:new, :create]
	before_action :check_admin, :only => [:new, :create]
	before_action :set_user, only: [:show, :edit, :update, :destroy]
	before_action :check_allowed, only: [:show, :edit, :update, :destroy]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
	@user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
	@user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
  	uploaded_io = params[:user][:avatar]
  	if uploaded_io
		file_name=SecureRandom.hex
		File.open(Rails.root.join('public', 'images', file_name), 'wb') do |file|
		file.write(uploaded_io.read)
	   end
	end
    @user = User.new(user_params)
	if uploaded_io; @user.photo = file_name; end	
    lev = 2
    if params[:user_level]
		lev = params[:user_level]
	end
	@user.level=lev	
    if @user.save
      flash[:notice] = "You signed up successfully"
      redirect_to :login
    else
      flash[:error] = "Form is invalid"
	  render :new
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
	@user = User.find(params[:id])
	uploaded_io = params[:user][:avatar]
	lev = 2
	del = params[:del_photo]
	org_name = @user.photo
	if uploaded_io
		file_name=SecureRandom.hex
		print "file_name"
		File.open(Rails.root.join('public', 'images', file_name), 'wb') do |file|
			file.write(uploaded_io.read)
		end
		@user.photo = file_name
		
	end
	if del
		file_name=nil
		File.delete(Rails.root.join('public', 'images', org_name))
		@user.photo = file_name
	end
	if params[:user_level]
		lev = params[:user_level]
		@user.level=lev	
		@user.save
	end
	if @user.update(user_params)
		flash[:notice]= 'User was successfully updated.' 
		@user.save
		redirect_to @user 
	else
		render 'edit'
	end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
	usr_id = @user.id	
    @user.destroy
    if session[:user_id] == usr_id
		reset_session
		redirect_to :login 
	else 
		redirect_to users_url 
	end
    flash[:notice]='User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
		if params[:id] 
			@user = User.find(params[:id])
		else
			@user = User.find(session[:user_id])
		end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :middle_name, :surname, :birth_date, :address, :mobile, :level, :email, :photo, :notes, :username, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<style>
 .field input {
	 min-width:150px;
 }
 .select-tag {
	 width:152px;
 }
/* .secondary {
	 display:table-col;
	 max-width:250px;
	 opacity:0.1;
 }
 .secondary:hover {
	 opacity:1;
 }
 .secondary:active {
	 opacity:1;
 }*/	
</style>
<%= form_for(@user, :class=>"contact_form") do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
		 <% if @user.photo %>
			<%= image_tag('/public/images/'+@user.photo, :class=>"upl-img")%><br/>
			<%= check_box_tag :del_photo , 1 %> Delete photo<br/>
			<% else %>
			<%= image_tag("/public/images/no_avatar.jpeg", :class=>"upl-img")%><br/>
		 <% end %>
		<%= f.file_field :avatar, multipart: true, :class => "file-browser" %>
  </div>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username, :class=>"small-text"  %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password, :class=>"small-text"  %>
  </div>
  <div class="field">
    Confirm pass:
    <%= f.password_field :password_confirmation, :class=>"small-text"  %>
  </div>
  
  <div class="secondary">
	  <% if session[:user_id] %>
		<% if User.find(session[:user_id]).level==0 %>
			<% if params[:id] && User.find(params[:id]).level==0 %>
			<% else %>
			  <div class="field">  
				  <%= f.label "user level" %>
				  <select id="user_level" name="user_level" class="select-tag">
					<option value=1 <%= @user.level==1 ? "selected" : "" %>>Power user</option>
					<option value=2 <%= @user.level==2 ? "selected" : "" %>>Reader</option>
				  </select> 
			  </div>
		   <% end %>
		 <% end %>
		<!--<% if User.find(session[:user_id]).level==1 %>
			<% if params[:id] and  User.find(params[:id]).level!=0 %>
			  <div class="field">  
				  <%= f.label "user level" %>
				  <select id="user_level" name="user_level" class="select-tag">
				  <option value=1 <%= @user.level==1 ? "selected" : "" %>>Power user</option>
				  <option value=2 <%= @user.level==2 ? "selected" : "" %>>Reader</option>
				  </select> 
			  </div>
			 <% end %>
		 <% end %> -->
	  <% end %>
	  </br>
	  <div class="field">
		<%= f.label :name %>
		<%= f.text_field :name, :class=>"small-text"  %>
	  </div>
	  <div class="field">
		<%= f.label :middle_name %>
		<%= f.text_field :middle_name, :class=>"small-text"  %>
	  </div>
	  <div class="field">
		<%= f.label :surname %>
		<%= f.text_field :surname, :class=>"small-text"  %>
	  </div>
	  <div class="field">
		<%= f.label :birth_date %>
		<%= f.text_field :birth_date, :type=> "date", :value=> ( @user.birth_date ? @user.birth_date.strftime("%F") : "") %>
	  </div>
	  <div class="field">
		<%= f.label :address %><br>
		<%= f.text_area :address, :rows=>"5", :class=>"wide-text"  %>
	  </div>
	  <div class="field">
		<%= f.label :mobile %>
		<%= f.text_field :mobile, :class=>"small-text"  %>
	  </div>
	  <div class="field">
		<%= f.label :email %><br>
		<%= f.text_field :email, :class=>"wide-text"  %>
	  </div>
	  <div class="field">
		<%= f.label :notes %><br>
		<%= f.text_area :notes, :cols=>"30", :rows=>"5", :class=>"wide-text"  %>
	  </div>
  </div>
<div class="float-save"><input type="submit" value="Save" class="button"></div>
<div id="top-save"><input type="submit" value="" class="button"></div>
<% end %>

app/views/users/edit.html.erb
<% if params[:id] and User.find(params[:id]).level==0 and @current_user.level!=0 %>
<%= controller.redirect_to :denied %>
<% else %>
<div class="back-link"><%= link_to image_tag("dark_icons/undow.png", :width=>"24", :class=>"link-img"), :back %></div>
<div class="list-link"><%= link_to image_tag("dark_icons/view_listw.png", :width=>"24", :class=>"link-img"), users_path %> </div>
<h1>Edit User</h1>

<%= render 'form' %>
<% end %>

app/views/users/index.html.erb
	<style>	
		table, th, td {
			border: 0px;
			border-collapse: collapse;
			vertical-align: middle;
		}
		th, td {
			padding: 5px;
		}
		tr:nth-child(even) {
			background-color: #E5E5E5
		}
		td {
			max-width: 350px;
			overflow: hidden;
			text-overflow: ellipsis;
			white-space: nowrap;
		}
		.tdd {
			max-width: 100px;
			overflow: hidden;
			text-overflow: ellipsis;
			white-space: nowrap;
		}	
		.image-upload > input {
			display: none;
		}
		/*.updImg {
			display: block;
			margin: auto;
			align: left;*/
		}
		.tdimg {
			width: 15px;
			max-width: 15px;
			width-max: 15px;
		}
		.thimg {
			width: 15px;
			max-width: 15px;
			width-max: 15px;
		}
		.meh {
			display: inline-block;
		}
	</style>
<% if @current_user.level < 2  %>

<h1>Users <%= link_to image_tag("dark_icons/plus_1.png", :width=>"20", :height=>"20"), new_user_path(id: params[:id]) %>	</h1>

    <% @users.each do |user| %>
	 <% if user.level==0 && @current_user.level != 0 %>
	 <% else %>	 
		<table>
		  <body>
			  <tr>
				<td><% if user.photo %>
						<%= image_tag('/public/images/'+user.photo, :class=>"avatar") %>
					<% else %>
						<%= image_tag("/public/images/no_avatar.jpeg", :class=>"avatar")%>
					<% end %>
				</td>
				<td>
					<h3  style="color:black;"><%= link_to user.username, user %> <%=link_to image_tag("dark_icons/edit.png", :width=>"13", :height=>"13"), edit_user_path(user) %></h3>	
					<%= user.name %> <%= user.surname %> </br>
				    <p style="color:gray;"><%= user.notes %></p>
				</td>
			 </tr>
		  </body>
		</table>
     <% end %>
    <% end %>

<% else %>
<%= controller.redirect_to :denied %>
<% end %>

app/views/users/new.html.erb
<div class="back-link"><%= link_to image_tag("dark_icons/undow.png", :width=>"24", :class=>"link-img"), :back %></div>
<div class="list-link"><%= link_to image_tag("dark_icons/view_listw.png", :width=>"24", :class=>"link-img"), users_path %> </div>
<h1>New User</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<% if (session[:user_id] && @current_user.level == 0)  or (params[:id] && User.find(params[:id]).level!=0) %>
<div class="back-link"><%= link_to image_tag("dark_icons/undow.png", :width=>"24", :class=>"link-img"), :back %></div>
<div class="list-link"><%= link_to image_tag("dark_icons/view_listw.png", :width=>"24", :class=>"link-img"), users_path %> </div>
<h1>User <%= @user.username %></h1>
<%=link_to image_tag("dark_icons/tools_1.png", :width=>"15", :height=>"15"), edit_user_path(@user) %> 
<% if User.find(params[:id]).level!=0 %> 
	<%= link_to image_tag("dark_icons/trash.png", :width=>"15", :height=>"15"), user_path(@user), method: :delete,
		data: { confirm: 'Are you sure?' } %> 
<% end %>
<table>
	<tr>
		<td rowspan="8" width="120">
		 <% if @user.photo %>
			<%= image_tag('/public/images/'+@user.photo, :class=>"upl-img")%>
			<% else %>
			<%= image_tag("/public/images/no_avatar.jpeg", :class=>"upl-img")%>
			<% end %>
		</td>
	</tr>
	<tr>
		<td width="100">
		  <strong>Username:</strong>
		</td>
		<td>
		  <%= @user.username %>
		</td>
	</tr>
	<tr>
		<td width="100">
		  <strong>Name:</strong>
		</td>
		<td>
		  <%= @user.name %>
		</td>	
		<td>
		  <%= @user.middle_name %>
		</td>
		<td>
		  <%= @user.surname %>
		</td>
	</tr>
		<td>
		  <strong width="100">Birth date:</strong>
		</td>
		<td>
		  <%= @user.birth_date %>
		</td>
	</tr>
	<tr>

		<td>
		  <strong width="100">Address:</strong>
		</td>
		<td>
		  <%= @user.address %>
		</td>

	</tr>
	<tr>
		<td>
		  <strong width="100">Mobile:</strong>
		</td>
		<td>
		  <%= @user.mobile %>
		</td>

	</tr>
	<tr>
		<td>
		  <strong width="100">Email:</strong>
		</td>
		<td>
		  <%= @user.email %>
		</td>

	</tr>
	<tr>
		<td>
		  <strong width="100">Notes:</strong>
		</td>
		<td>
		  <%= @user.notes %>
		</td>
	</tr>
	<tr><td></br></td></tr>
	<tr>
		<td colspan="5">
			<% if @user.books.any? %>
				<strong>Books (<%= @user.books.count %>)</br></strong>
				<table class="sub-result">
					 <tr bgcolor="#aaFFaa">
					  <th>Title</th>
					  <th>Sub - title</th>
					  <th>Year</th>
					  <th>Synopsis</th>
					  </tr>

						<%= render @user.books %> 

					</table>
			<% else %> (0)
			<% end %>
		</td>
	</tr>
</table>
<% else %>
<%= controller.redirect_to :denied %>
<% end %>