config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", :locale => /en|pl/ do
    resource :sessions do
      collection {post :login_attempt }
      end
      root :to => 'sessions#login'
      get "signup", :to => "users#new"
      get "login", :to => "sessions#login"
      get "logout", :to => "sessions#logout"
      get "home", :to => "welcome#index"
      get "profile", :to => 'users#show'
      get "setting", :to => "users#edit"
      resources :users
    
      get 'welcome/index'
      get 'welcome/hidden'
      get 'welcome/search_all'
      get 'welcome/denied', as: 'denied'
      get '/parts/live_search', to: 'parts#live_search', as: 'search'
      get '/pcbs/live_search', to: 'pcbs#live_search', as: 'lookup'
      get '/parts/add_qte', to: 'parts#add_qte', as: 'add_qte'
      get '/parts/del_qte', to: 'parts#del_qte', as: 'del_qte'
      get '/pcbs/add_all', to: 'pcbs#add_all', as: 'add_all'
      get '/shopping_lists/upd_all', to: 'shopping_lists#upd_all', as: 'upd_all'
    
      resources :parts do
        collection {post :import }
        collection {post :move_location }
        collection {post :move_manufacturer }
        collection {post :move_package }
        collection {post :move_type }
        collection {post :add_qte }
        collection {post :set_qte }
        collection {post :del_qte }
        collection {post :add_qte_s }
        collection {post :del_qte_s }
      end
      resources :locations do
      collection {post :import }
      end
      resources :packages do
      collection {post :import }
      end
      resources :manufacturers do
      collection {post :import }
      end
      resources :types do
      collection {post :import }
      end
      
      resources :movies do
      collection {post :import }
      collection {get :call_api }
      end
      resources :mformats do
      collection {post :import }
      end
      resources :mlanguages do
      collection {post :import }
      end
      resources :msubtitles do
      collection {post :import }
      end
      resources :mtypes do
      collection {post :import }
      end
      resources :myears do
      collection {post :import }
      end
      resources :qualities do
      collection {post :import }
      end
      resources :threeds do
      collection {post :import }
      end
      resources :genres
      
      resources :books, :authors, :publishers do
      collection {post :import }
      end
      
      resources :pcbs do
        collection {post :import }
        end
    
      resources :projects do
        collection {post :import }
        end
      
      resources :shopping_lists

  end

  
end

app/models/quality.rb
class Quality < ActiveRecord::Base
	has_many :movies, dependent: :nullify
  def self.import(file)	
	CSV.foreach(file.path, headers: true) do |row|
		Quality.create! row.to_hash
	end
	end
end

app/controllers/qualities_controller.rb
class QualitiesController < ApplicationController
	require 'will_paginate/array'
  before_action :set_quality, only: [:show, :edit, :update, :destroy]

  # GET /qualities
  # GET /qualities.json
  def index
    @qualities = Quality.all.order('quality ASC').paginate(:page => params[:page], :per_page => 25)
  end

  # GET /qualities/1
  # GET /qualities/1.json
  def show
		@quality = Quality.find(params[:id])
		@movies= @quality.movies.order('name asc')
  end

  # GET /qualities/new
  def new
    @quality = Quality.new
  end

  # GET /qualities/1/edit
  def edit
  end

  # POST /qualities
  # POST /qualities.json
  def create
    @quality = Quality.new(quality_params)

    respond_to do |format|
      if @quality.save
        format.html { redirect_to @quality, notice: "Quality created" }
        format.json { render :show, status: :created, location: @quality }
      else
        format.html { render :new, error: "Error when saving" }
        format.json { render json: @quality.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /qualities/1
  # PATCH/PUT /qualities/1.json
  def update
    respond_to do |format|
      if @quality.update(quality_params)
        format.html { redirect_to @quality, notice: "Quality saved" }
        format.json { render :show, status: :ok, location: @quality }
      else
        format.html { render :edit, error: "Error when saving" }
        format.json { render json: @quality.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qualities/1
  # DELETE /qualities/1.json
  def destroy
    @quality.destroy
    respond_to do |format|
      format.html { redirect_to qualities_url, notice: "Quality deleted" }
      format.json { head :no_content }
    end
  end

  # Extra DEFs
  
  def import
		@file = params[:file]
		@fcsv = false
		if @file; @fcsv = File.extname(@file.path)=='.csv' ? true : false; end
		if @file && @fcsv
			Quality.import(params[:file])
			flash[:notice]="Import completed"
			else
			flash[:error]="Import failed"
			end
	redirect_to qualities_path
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quality
      @quality = Quality.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quality_params
      params.require(:quality).permit(:quality, :notes)
    end
end

app/helpers/qualities_helper.rb
module QualitiesHelper
end

app/views/qualities/_form.html.erb
<%= form_for(@quality) do |f| %>
  <% if @quality.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quality.errors.count, "error") %> prohibited this quality from being saved:</h2>

      <ul>
      <% @quality.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label "Quality" %><br>
    <%= f.text_field :quality, :class=>"wide-text" %>
  </p>
  <p>
    <%= f.label "Notes" %><br>
    <%= f.text_area :notes, :cols=>"30", :rows=>"5", :class=>"wide-text"  %>
  </p>
<div class="float-save"><input type="submit" value="Save" class="button"></div>
<div id="top-save"><input type="submit" value="" class="button"></div>
<% end %>

app/views/qualities/edit.html.erb
<div class="list-link"><%= link_to image_tag("dark_icons/view_listw.png", :width=>"24", :class=>"link-img"), qualities_path %> </div>
<div class="back-link"><%= link_to image_tag("dark_icons/undow.png", :width=>"24", :class=>"link-img"), :back %></div>
<h1> Edit quality </h1>

<%= render 'form' %>

app/views/qualities/index.html.erb
	<style>	
		table, th, td {
			border: 1px solid blue;
			border-collapse: collapse;
			vertical-align: middle;
		}
		th, td {
			padding: 5px;
		}
		tr:nth-child(even) {
			background-color: #eeeeff
		}
		td {
			max-width: 350px;
			overflow: hidden;
			text-overflow: ellipsis;
			white-space: nowrap;
		}
		.tdd {
			max-width: 100px;
			overflow: hidden;
			text-overflow: ellipsis;
			white-space: nowrap;
		}	
		.image-upload > input {
			display: none;
		}
		/*.updImg {
			display: block;
			margin: auto;
			align: left;*/
		}
		.tdimg {
			width: 15px;
			max-width: 15px;
			width-max: 15px;
		}
		.thimg {
			width: 15px;
			max-width: 15px;
			width-max: 15px;
		}
		.meh {
			display: inline-block;
		}
	</style>
<div class="list-link"><%= link_to image_tag("dark_icons/view_listw.png", :width=>"24", :class=>"link-img"), qualities_path %> </div>
<div class="back-link"><%= link_to image_tag("dark_icons/undow.png", :width=>"24", :class=>"link-img"), :back %></div>
<h1>Qualities <%= link_to image_tag("dark_icons/plus_1.png", :width=>"20", :height=>"20"), new_quality_path %>	</h1>
<div class="import">
	<%= form_tag import_qualities_path, multipart: true do %>
	<%= file_field_tag :file, :class => "file-browser"  %>
		<input type="submit" value="Import" class="button">
		
	<% end %></div>

<table>
    <tr bgcolor="#aaaaff">
      <th>ID</th>
      <th>Quality</th>
      <th>Notes</th>
      <th>Pts</th>
    </tr>

    <% @qualities.each do |quality| %>
      <tr>
        <td><%= quality.id %></td>
        <td><%= link_to quality.quality, quality_path(quality) %></td>
        <td><%= quality.notes %></td>
		<td><% if quality.movies.any? %>
					<%= quality.movies.count %>
			<% else %> 0
			<% end %> </td>		
		<td class="tdimg"><%=link_to image_tag("dark_icons/tools_1.png", :width=>"13", :height=>"13"), edit_quality_path(quality) %></td>
      </tr>
    <% end %>
</table>
<%= will_paginate @qualities %>

app/views/qualities/new.html.erb
<div class="list-link"><%= link_to image_tag("dark_icons/view_listw.png", :width=>"24", :class=>"link-img"), qualities_path %> </div>
<div class="back-link"><%= link_to image_tag("dark_icons/undow.png", :width=>"24", :class=>"link-img"), :back %></div>
<h1> New quality </h1>

<%= render 'form' %>

app/views/qualities/show.html.erb
<div class="list-link"><%= link_to image_tag("dark_icons/view_listw.png", :width=>"24", :class=>"link-img"), qualities_path %> </div>
<div class="back-link"><%= link_to image_tag("dark_icons/undow.png", :width=>"24", :class=>"link-img"), :back %></div>
<h1>Quality <%= @quality.id %></h1>
<%=link_to image_tag("dark_icons/tools_1.png", :width=>"15", :height=>"15"), edit_quality_path(@quality) %> <%=link_to image_tag("dark_icons/trash.png", :width=>"15", :height=>"15"), quality_path(@quality), method: :delete,
		data: { confirm: 'Are you sure?' } %> <%= link_to image_tag("dark_icons/plus_1.png", :width=>"15", :height=>"15"), new_quality_path %>
<table style="width:500px;">
	<tr>
		<td>
			<strong>Quality:</strong>
			<%= @quality.quality %>
		</td>
	</tr>

	<tr>
		<td>
			<strong>Notes:</strong></br>
			<%= @quality.notes %>
		</td>
	</tr>
	<tr>
		<td colspan="5">
			<b></br>Movies </b>
			<% if @quality.movies.any? %>
				(<%= @quality.movies.count %>)</br>
				<table class="sub-result">
				<col width=80 >
				<col width=100 >
				<col width=200 >
					 <tr bgcolor="#aaaaFF">
					  <th>Title</th>
					  <th>Sub title</th>
					  <th>Sunopsis</th>
					  </tr>

						<%= render @quality.movies %> 

					</table>
			<% else %> (0)
			<% end %>
					
	</table>