config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", :locale => /en|pl/ do
    resource :sessions do
      collection {post :login_attempt }
      end
      root :to => 'sessions#login'
      get "signup", :to => "users#new"
      get "login", :to => "sessions#login"
      get "logout", :to => "sessions#logout"
      get "home", :to => "welcome#index"
      get "profile", :to => 'users#show'
      get "setting", :to => "users#edit"
      resources :users
    
      get 'welcome/index'
      get 'welcome/hidden'
      get 'welcome/search_all'
      get 'welcome/denied', as: 'denied'
      get '/parts/live_search', to: 'parts#live_search', as: 'search'
      get '/pcbs/live_search', to: 'pcbs#live_search', as: 'lookup'
      get '/parts/add_qte', to: 'parts#add_qte', as: 'add_qte'
      get '/parts/del_qte', to: 'parts#del_qte', as: 'del_qte'
      get '/pcbs/add_all', to: 'pcbs#add_all', as: 'add_all'
      get '/shopping_lists/upd_all', to: 'shopping_lists#upd_all', as: 'upd_all'
    
      resources :parts do
        collection {post :import }
        collection {post :move_location }
        collection {post :move_manufacturer }
        collection {post :move_package }
        collection {post :move_type }
        collection {post :add_qte }
        collection {post :set_qte }
        collection {post :del_qte }
        collection {post :add_qte_s }
        collection {post :del_qte_s }
      end
      resources :locations do
      collection {post :import }
      end
      resources :packages do
      collection {post :import }
      end
      resources :manufacturers do
      collection {post :import }
      end
      resources :types do
      collection {post :import }
      end
      
      resources :movies do
      collection {post :import }
      collection {get :call_api }
      end
      resources :mformats do
      collection {post :import }
      end
      resources :mlanguages do
      collection {post :import }
      end
      resources :msubtitles do
      collection {post :import }
      end
      resources :mtypes do
      collection {post :import }
      end
      resources :myears do
      collection {post :import }
      end
      resources :qualities do
      collection {post :import }
      end
      resources :threeds do
      collection {post :import }
      end
      resources :genres
      
      resources :books, :authors, :publishers do
      collection {post :import }
      end
      
      resources :pcbs do
        collection {post :import }
        end
    
      resources :projects do
        collection {post :import }
        end
      
      resources :shopping_lists

  end

  
end

app/models/project.rb
class Project < ActiveRecord::Base
require 'csv'
require 'rails/all'
  validates :name,  presence: true, allow_blank: false
  validates :code,  presence: true, allow_blank: false, :uniqueness => {:case_sensitive => false}
  has_many :pcb_projects
  has_many :pcbs, through: :pcb_projects
  has_many :part_projects
  has_many :parts, through: :part_projects
  has_many :photos, :dependent => :destroy
  accepts_nested_attributes_for :photos, allow_destroy: true
  has_many :documents, :dependent => :destroy
  accepts_nested_attributes_for :documents, allow_destroy: true
validate :validate_end
  
  
def self.search(search)
	where("name LIKE :search OR version LIKE :search OR notes LIKE :search OR description like :search OR code like :search",search: "%#{search}%")
end

def self.pcbs_cost(id)
	query = <<-SQL
	  select sum(z.quantity * b.quantity * case when c.p_price is null then 0 else c.p_price end) as pr_cost
		from projects x
		left join pcb_projects z on z.project_id=x.id
		left join pcbs a on a.id=z.pcb_id
		left join part_pcbs b on a.id=b.pcb_id
		left join parts c on b.part_id=c.id
		where x.id=#{id}
	SQL

self.find_by_sql(query)
end

def self.pcbs_pr_cost(id)
	query = <<-SQL
	  select sum(z.quantity * a.cost) as pr_cost
		from projects x
		left join pcb_projects z on z.project_id=x.id
		left join pcbs a on a.id=z.pcb_id
		where x.id=#{id}
	SQL

self.find_by_sql(query)
end




def self.parts_cost(id)
	query = <<-SQL
	  select sum(b.quantity * case when c.p_price is null then 0 else c.p_price end) as pr_cost
		from projects x
		left join part_projects b on x.id=b.project_id
		left join parts c on b.part_id=c.id
		where x.id=#{id}
	SQL

self.find_by_sql(query)
end

def self.all_cost(id)
	query = <<-SQL
	  select round(sum(z.quantity * b.quantity * case when c.p_price is null then 0 else c.p_price end), 2) as pr_cost
		from projects x
		left join pcb_projects z on z.project_id=x.id
		left join pcbs a on a.id=z.pcb_id
		left join part_pcbs b on a.id=b.pcb_id
		left join parts c on b.part_id=c.id
		where x.id=#{id}
	SQL

self.find_by_sql(query)
end

def self.latest_cost(id)
	query = <<-SQL
	  select round(sum(z.quantity * b.quantity * case when c.p_price is null then 0 else c.p_price end), 2) as pr_cost
		from projects x, (select name, max(version) as version from pcbs group by name) table1
		left join pcb_projects z on z.project_id=x.id
		left join pcbs a on a.id=z.pcb_id
		left join part_pcbs b on a.id=b.pcb_id
		left join parts c on b.part_id=c.id
		where x.id=#{id}
		and a.name=table1.name and a.version=table1.version
	SQL

self.find_by_sql(query)
end

def self.all_parts(id)
	query = <<-SQL
	  select sum(b.quantity * z.quantity) as quantity, b.part_id, c.*, case when c.p_type is null then "" else c.p_type end as type
		from projects x
		left join pcb_projects z on z.project_id=x.id
		left join pcbs a on a.id=z.pcb_id
		left join part_pcbs b on a.id=b.pcb_id
		left join parts c on b.part_id=c.id
		where x.id=#{id} and b.part_id is not null
		group by b.part_id
	SQL

self.find_by_sql(query)
end

def self.latest_parts(id)
	query = <<-SQL
	  select sum(b.quantity * z.quantity) as quantity, b.part_id, c.*, case when c.p_type is null then "" else c.p_type end as type
		from projects x, (select name, max(version) as version from pcbs group by name) table1
		left join pcb_projects z on z.project_id=x.id
		left join pcbs a on a.id=z.pcb_id
		left join part_pcbs b on a.id=b.pcb_id
		left join parts c on b.part_id=c.id
		where x.id=#{id} and b.part_id is not null
		and a.name=table1.name and a.version=table1.version
		group by b.part_id
	SQL

self.find_by_sql(query)
end

def self.import(file)	
	CSV.foreach(file.path, headers: true) do |row|
		Project.create! row.to_hash
	end
end

def self.all_csv(options = {})
	CSV.generate(options) do |csv|
	  csv << column_names
	  self.all.each do |row|
		csv << row.attributes.values_at(*column_names)
	  end
	end
end

def self.mob_csv(options = {})
	id = options[:id]
	options = {}
	sub_part_names = ['pcb','pcb_ver','part_number','m_full_name', 'part_name', 'p_type','pk_name', 'p_note', 'p_price', 'quantity', 'line_price']
	part_names = ['part_number','m_full_name', 'part_name', 'p_type','pk_name', 'p_note', 'p_price', 'quantity', 'line_price']
	pcb_names = ['name', 'version']
	CSV.generate(options) do |csv|
		csv << sub_part_names
		PartProject.project_parts(id).each do |row|
			csv << row.attributes.values_at(*sub_part_names)
		end
		Project.find(id).pcbs.each do |row|
			csv << row.attributes.values_at(*pcb_names)
			PartPcb.pcb_parts(row.id, id).each do |part|
				csv << part.attributes.values_at(*sub_part_names)
			end
		end
	end
end

private

def compare_dates
  if self.end_date.nil? or (self.start_date <= self.end_date)
    true
  else
    false
  end
end

def validate_end
  errors.add("End date", "cannot be before start date.") unless compare_dates
end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	require 'rails/all'
	require 'will_paginate/array'
	require 'csv'
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all.order("code ASC, version DESC").paginate(:page => params[:page], :per_page => 5)
       
	if params[:search]
		@projects = Project.search(params[:search]).order(sort_column + ' ' + sort_direction).paginate(:page => params[:page], :per_page => 5)
	else
		@projects = Project.all.order(sort_column + ' ' + sort_direction).paginate(:page => params[:page], :per_page => 5)
	end
		Rails.configuration.pr_sort = sort_column 
		Rails.configuration.pr_dir = sort_direction
	respond_to do |format|
	  format.html
	  format.tsv { send_data Project.all.all_csv, filename: "all-projects-#{Date.today}.csv" }
	end  
	
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
	@project = Project.find(params[:id])
	respond_to do |format|
	  format.html
	  format.csv { send_data Project.mob_csv(id: params[:id]), filename: "project-bom-#{Date.today}.csv" }
	end  
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
  
    @project = Project.new(project_params)
	time = Time.new
	uploaded_io = params[:project][:background]
	file_name="project-background.png"
	if uploaded_io
		file_name=SecureRandom.hex
		File.open(Rails.root.join('public', 'images', 'backgrounds', file_name), 'wb') do |file|
			file.write(uploaded_io.read)
		end
	 end
    respond_to do |format|
      if @project.save
		# Updating PCB quantity
		nums_id=params[:project][:pcb_ids]
			if nums_id
				nums_id.each do |id|
					component='quantity_'+id.to_s
					if id and id!=''
						val = params["quantity_#{id}"]
						@pp=PcbProject.where(project_id: "#{@project.id}", pcb_id: "#{id}").take
						@pp.upd_qte(@pp.id, val)
					end
				end
			end  
		# Updating Part quantity
		parts_id=params[:project][:part_ids]
			if parts_id
				parts_id.each do |id|
					p_component='p_quantity_'+id.to_s
					if id and id!=''
						p_val = params["p_quantity_#{id}"]
						@p_p=PartProject.where(project_id: "#{@project.id}", part_id: "#{id}").take
						@p_p.upd_qte(@p_p.id, p_val)
					end
				end
			end      
		@project.log=time.strftime("%e %b %Y %H:%M")+": Project created\n"
		@project.save
		if params[:image]
		  params[:image].each do |picture|      
			@project.photos.create(:image=> picture)
			# Don't forget to mention :avatar(field name)
			end
		 end
		 # saving files
		 if params[:file]
		  params[:file].each do |file|      
			@project.documents.create(:file=> file)
			# Don't forget to mention :avatar(field name)
			end
		 end
		if params[:text_log]!=""		
			log = time.strftime("%e %b %Y %H:%M")+": "+ params[:text_log]
			@project.log+=log+"\n"
		end
		if uploaded_io; @project.background = file_name; end	
		@project.save
		flash[:notice] = "Project created"
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, error: "Error when saving" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
  params[:parent_id]=params[:project][:parent_id]
		# background saving
		uploaded_io = params[:project][:background]
		del = params[:del_photo]
		org_filename="default.png"
		file_name="project-background.png"
		time = Time.new
		if uploaded_io
			file_name=SecureRandom.hex
			File.open(Rails.root.join('public', 'images',  'backgrounds',file_name), 'wb') do |file|
			file.write(uploaded_io.read)
		 end	
		end
    respond_to do |format|
      if @project.update(project_params)          
		 # saving images
		 if params[:image]
		  params[:image].each do |picture|      
			@project.photos.create(:image=> picture)
			# Don't forget to mention :avatar(field name)
			end
		 end
		 # saving files
		 if params[:file]
		  params[:file].each do |file|      
			@project.documents.create(:file=> file)
			# Don't forget to mention :avatar(field name)
			end
		 end
		 # saving logs
		if params[:text_log]!=""
			log = time.strftime("%e %b %Y %H:%M")+": "+ params[:text_log]
			if @project.log; @project.log+=log+"\n"; else @project.log=log+"\n"; end
		end
		# deleting selected images
		if params[:destruction]
			Photo.where(:project_id=>@project.id).where(:id => params[:destruction]).destroy_all
		end
		# deleting selected files
		if params[:deletions]
			Document.where(:project_id=>@project.id).where(:id => params[:deletions]).destroy_all
		end
		# updating background
		if del
			File.delete(Rails.root.join('public', 'images', 'backgrounds', @project.background))
			file_name=org_filename;
		end
		if uploaded_io or del; @project.background = file_name; end	
		# Updating PCB quantity
		nums_id=params[:project][:pcb_ids]
			if nums_id
				nums_id.each do |id|
					component='quantity_'+id.to_s
					if id and id!=''
						val = params["quantity_#{id}"]
						@pp=PcbProject.where(project_id: "#{@project.id}", pcb_id: "#{id}").take
						@pp.upd_qte(@pp.id, val)
					end
				end
			end    
		# Updating Part quantity
		parts_id=params[:project][:part_ids]
			if parts_id
				parts_id.each do |id|
					p_component='p_quantity_'+id.to_s
					if id and id!=''
						p_val = params["p_quantity_#{id}"]
						@p_p=PartProject.where(project_id: "#{@project.id}", part_id: "#{id}").take
						@p_p.upd_qte(@p_p.id, p_val)
					end
				end
			end  
		# saving all changes
		@project.save
		flash[:notice] = "Project saved"
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
		flash[:error] = "Error when saving project"
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
	org_name = @project.background
	begin
		File.delete(Rails.root.join('public', 'images', 'backgrounds', org_name));
	rescue => ex
	end
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

	def import
		@file = params[:file_imp]
		@fcsv = false
		if @file; @fcsv = File.extname(@file.path)=='.csv' ? true : false; end
		if @file && @fcsv
			Project.import(params[:file_imp])
		flash[:notice] = "Import completed"
		else
		flash[:error] = "Import failed"
			end
		redirect_to projects_path
	end
def del_photos
end
helper_method :del_photos
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:code, :name, :version, :start_date, :end_date, :notes, :description, {:part_ids => []}, {:pcb_ids => []}, :log, :folder_location, :background)
    end
	def sort_column
		params[:sort] || Rails.configuration.pr_sort || "code"
	end
	def sort_direction
		params[:direction] || Rails.configuration.pr_dir || "asc"
	end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<style>
	tr {
		vertical-align: top;
	}
	.row {
		  display: inline-block;
		  margin-left:5px;
		  height:280px;
		  width: 100%;
		  overflow-y: auto;
		}
	.basic {
			width:375px;
			margin-top:0px;
			padding: 7px;  
			height: 300px;
		}
	.life-search-results {
		padding:7px;
		}
	.contain {
		display: inline-block; 
		position:relative;
		}
	.div_right {
		display: inline;
		float:right;
		}
	.div_left {
		display: inline;
		float:left;
		min-width:300px;
		max-width:300px;
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: pre;	
		}
	#big-search-box {
		margin-bottom:5px;
		}
	.lister3 {
		padding:0;  
		max-height: 145px; 
		width:100%;
		overflow-y: auto;
	} 
	.lister3 {
		padding:0;  
		max-height: 145px; 
		width:100%;
		overflow-y: auto;
	} 
	.log-container {
		margin0;
		padding:0;  
		width:450px;
		height: 165px;
	}	
	#images {
		border:1px solid #4CAF50;
		width:292px;
		height:350px;
	}
	.del_box {
		margin-left:-17px;
		max-width:250px;
	}
	.project-upper-left-files {
		padding:3px;
		height:70px;
		width:400px;
		overflow-y:auto;
	}
		.ids_array {
			display:none;
		}
		#hidden {
			display:none;
		}
</style>
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<table>
	<tr align="left">
	  <td>
		<%= f.label "Name" %><br>
		<%= f.text_field :name, :class=>"wide-text" %>
	  </td>
	  <% if Rails.configuration.developer=="true" %>
		  <td>
			<%= f.label "Code" %><br>
			<%= f.text_field :code, :class=>"ultra-small-text" %>
		  </td>
		  <td>
			<%= f.label "Ver." %><br>
			<%= f.text_field :version, :class=>"ultra-small-text"  %>
		  </td>
	  <% else %>
		  <td colspan="2">
			<%= f.label "Code" %><br>
			<%= f.text_field :code, :class=>"ultra-small-text" %>
		  </td>	  
	  <% end %>
	  <td rowspan="5">
			<fieldset class="basic">
				<legend style="color:green;">PCBs <%= link_to image_tag("dark_icons/plus transparent.png", :width=>"13", :height=>"13"), new_pcb_path, :target=>'_blank' %></legend>			
				 <div class="row" style="display:inline-block;">	
					<div id="live-search-results">
						<%= collection_check_boxes(:project, :pcb_ids, Pcb.all.order('name ASC'), :id, :pcb_list2) do |b| %>
						<div class="col-xs-1">
							<div class="contain">
								<div class="div_left"  style="font-family:monospace;"><%= b.check_box(class: "check_box") +' '+ link_to(b.text, pcb_path(b.value), :target=>'_blank' ) %></div>
								<div class="div_right"><%=number_field('quantity_'+b.value.to_s, nil, min: "0", max: "1000", :value => if PcbProject.where(pcb_id: b.value, project_id: @project.id).take;  PcbProject.where(pcb_id: b.value, project_id: @project.id).take.quantity.to_s; else "0"; end, :class=>"ultra-small-text") %></div>
							</div>
						</div>
					<% end %>
					</div>
				</div>
				</div>
				</fieldset>
		</td>
	</tr>
	<tr>
	  <td colspan="3">
		<%= f.label "Folder location", :style=>"width: 8em;" %><br>
		<%= f.text_field :folder_location, :class=>"wide-text"  %>
	  </td>
	</tr>
	<tr>
	  <td>
		<%= f.label "Started" %><br>
		<%= f.text_field :start_date, :type=> "date", :value=> ( @project.start_date ? @project.start_date.strftime("%F") : "") %>
	  </td>
	</tr>
	<tr>
	  <td>
		<%= f.label "Finished" %><br>
		<%= f.text_field :end_date, :type=> "date", :value=> ( @project.end_date ? @project.end_date.strftime("%F") : "") %>
	  </td>
	</tr>
	<tr>
	  <td colspan="3">
		<%= f.label "Description" %><br>
		<%= f.text_area :description, :cols=>"30", :rows=>"10", :class=>"extra-wide-text" %>	  
	  </td>
	</tr>
	<tr>
	  <td colspan="3">
		Files : 
		<%= file_field_tag 'file[]', multipart: true, accept: '*/*', :class => "file-browser", :multiple=>"true" %><br/>
		<% if @project.documents.any? %>
		</br>Delete files:</br>
			<div class="project-upper-left-files">
				<% @project.documents.each do |doc| %>
					(<%= check_box_tag 'deletions[]', doc.id, false %> <%= doc.file_file_name %>)					
				<% end %>
			</div>
			<% end %>
	  </td>
	  <td rowspan="2">
		<div id="hidden"><div id="ids_array"><% Part.all.ids %></div></div> 
			<fieldset class="basic">
				<legend style="color:green;">Parts <%= link_to image_tag("dark_icons/plus transparent.png", :width=>"13", :height=>"13"), new_part_path, :target=>'_blank' %></legend>			
				 <form id="live-search-form" method="get" action="<%= search_path %>">
					  <input id="big-search-box" name="q" type="text" style="float:left;" />
					  <div id='loader' style="float:right;" ></div>
					</form>
				 <div class="row" style="display:inline-block; height:255px;">	
					<div id="live-search-results">
						<%= collection_check_boxes(:project, :part_ids, Part.all.order('part_name ASC'), :id, :part_list2) do |b| %>
						<div class="col-xs-8" id="single_line_<%= b.value.to_s %>" >
							<div class="contain">
								<div class="div_left"  style="font-family:monospace;"><%= b.check_box(class: "check_box") +' '+ link_to(b.text, part_path(b.value), :target=>'_blank', :title=> Part.find(b.value).part_number ) %></div>
								<div class="div_right"><%=number_field('p_quantity_'+b.value.to_s, nil, min: "0", max: "1000", :value => if PartProject.where(part_id: b.value, project_id: @project.id).take;  PartProject.where(part_id: b.value, project_id: @project.id).take.quantity.to_s; else "0"; end, :class=>"ultra-small-text") %></div>
							</div>
						</div>
					<% end %>
					</div>
				</div>
				</div>
				</fieldset>
		</td>
	</tr>
	<tr>
	  <td colspan="3">
		<%= f.label "Notes" %><br>
		<%= f.text_area :notes,:cols=>"30", :rows=>"10", :class=>"extra-wide-text" %>	  
	  </td>
	</tr>
	<tr>	
	  <td colspan="3">
		<%= f.label 'Logs' %><br>
			<fieldset class="log-container">
				<div class="lister3">
					<p>
						<%= simple_format(@project.log) %>
					</p>
				</div>
			</fieldset>
		<%= text_field_tag(:date_log, Time.new.to_s, :readonly => true, :class=>"small-text")%><%= text_field_tag(:text_log,"",:class=>"wider-wide-text") %>
	  </td>
	  <td colspan="3" rowspan="5" style="max-width:250px;">		
		<% if @project.photos.any? %>
			</br>Delete files:</br>
			<% @project.photos.each do |p| %>
			  <%= image_tag(p.image(:thumb)) %>
			  <%= check_box_tag 'destruction[]', p.id, false, class: "del_box" %>
			<% end %>
		<% end %>
	  </td>
	</tr>
	<tr>
	  <td colspan="2" >
		<%= f.label "Background image", :style=>"width: 9em;"  %><br>
		<%= f.file_field :background, multipart: true, accept: 'image/*', :class => "file-browser" %><br/>	 
		<% if @project.background and  @project.background!="default.png" %><%= check_box_tag :del_photo , 1 %> Delete photo<% end %>
	  </td>
	</tr>
	<tr>
	  <td colspan="1" rowspan="1">
		Images
		<%= file_field_tag 'image[]', multipart: true, accept: 'image/*', :class => "file-browser", :multiple=>"true" %>
	  </td>
	</tr>
	  <div class="actions">
		<div class="float-save"><input type="submit" value="Save" class="button"></div>
<div id="top-save"><input type="submit" value="" class="button"></div>
	  </div>
  </table>
<% end %>

app/views/projects/edit.html.erb
<div class="back-link"><%= link_to image_tag("dark_icons/undow.png", :width=>"24", :class=>"link-img"), :back %></div>
<div class="list-link"><%= link_to image_tag("dark_icons/view_listw.png", :width=>"24", :class=>"link-img"), projects_path %> </div>
<h1>Editing Project</h1>

<%= render 'form' %>

app/views/projects/index.html (copy).erb
<style>
table, th, td {
	border: 1px solid blue;
	border-collapse: collapse;
	vertical-align: middle;
}
th, td {
	padding: 5px;
}
tr:nth-child(even) {
	background-color: #FFECC8
}
td {
	max-width: 100px;
	overflow: hidden;
	text-overflow: ellipsis;
	white-space: nowrap;
}
.tdd {
	max-width: 100px;
	overflow: hidden;
	text-overflow: ellipsis;
	white-space: nowrap;
}	
.image-upload > input {
	display: none;
}
.tdimg {
	width: 15px;
	max-width: 15px;
	width-max: 15px;
}
.thimg {
	width: 15px;
	max-width: 15px;
	width-max: 15px;
}
.meh {
	display: inline-block;
}
</style>

<div class="back-link"><%= link_to image_tag("dark_icons/undow.png", :width=>"24", :class=>"link-img"), :back %></div>
<div class="list-link"><%= link_to image_tag("dark_icons/view_listw.png", :width=>"24", :class=>"link-img"), projects_path %> </div>
 <h1>Projects (<%=@projects.count %>) <%= link_to image_tag("dark_icons/plus_1.png", :width=>"20", :height=>"20"), new_project_path %> </h1> 
	<div class="meh">
	<%= form_tag import_projects_path, multipart: true do %>
		<div style="display: table-cell; width:290px;"><%= file_field_tag :file_imp, :class => "file-browser"  %></div>
		<div style="display: table-cell; padding-left:3px;"><input type="submit" value="Import" class="button"></div>
	<% end %> 
	<%= form_tag projects_path, :method => 'get' do %>
		<div style="display: table-cell; width:290px;"><%= text_field_tag :search, params[:search], :class => "search-tag" %></div>
		<div style="display: table-cell; padding-left:3px;""><input type="submit" value="Search" class="button" id="blue-button"></div>
	<% end %>	
	</div>
<table>
    <tr bgcolor="#FFA500">
      <th><%= sortable "code", "Code" %></th>
      <th><%= sortable "name", "Name" %></th>
      <th><%= sortable "version", "Version" %></th>
      <th><%= sortable "start_date", "Start date" %></th>
      <th><%= sortable "end_date", "End date" %></th>
      <th><%= sortable "description", "Description" %></th>
    </tr>

    <% @projects.each do |project| %>
      <tr valign="top">
        <td><%= link_to project.code, project %></td>
        <td><%= link_to project.name, project  %></td>
        <td><%= project.version %></td>
        <td><%= project.start_date %></td>
        <td><%= project.end_date %></td>
        <td style="max-width:300px;"><%= project.description %></td>
        <td class="tdimg"><%=link_to image_tag("dark_icons/tools_1.png", :width=>"13", :height=>"13"), edit_project_path(project) %></td>
		<td class="tdimg"><%=link_to image_tag("dark_icons/trash.png", :width=>"13", :height=>"13"), project_path(project),
		method: :delete,
		data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
</table>
<%= will_paginate @pcbs %>
 <% if @projects.count >0 %>
 <div class="download-link"><%= link_to image_tag("dark_icons/download.png", :width=>"24", :class=>"link-img"), projects_path(format: "tsv") %> </div>
 <% end %>

app/views/projects/new.html.erb
<div class="back-link"><%= link_to image_tag("dark_icons/undow.png", :width=>"24", :class=>"link-img"), :back %></div>
<div class="list-link"><%= link_to image_tag("dark_icons/view_listw.png", :width=>"24", :class=>"link-img"), projects_path %> </div>
<h1>New Project</h1>

<%= render 'form' %>